<?php

	/*
	THIS FILE WAS AUTOMATICALLY GENERATED BY MGB
	DO NOT MODIFY IT!

	DATE FILE WAS CREATED: 10 Mar 2025, 01:20
	*/

	// Database settings
	$db = array();

	$db['hostname'] = 'localhost';
	$db['dbname'] = 'mgb';
	$db['username'] = 'root';
	$db['password'] = '';
	$db['prefix'] = 'mgb_';

	$mgb_installation_complete = TRUE;
	$mgb_installation_timestamp = 1741569647;

?>